version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - 'DB_URL=postgres://root:pass@postgres:5432/news'

volumes:
  db: